### ISSUE TITLE
Copy资源到StreamingAssets的时候加个 AssetDatabase.Refresh()吧 手动刷新太麻烦

### ISSUE THREAD

**Issue by clksaaa** [mister91jiao/BundleMaster_IntegrateETTask#3]
[MenuItem("Tools/打开常用文件夹/打开沙盘目录PersistentDataPath")]
        public static void OpenPersistentDataPath()
        {
            Application.OpenURL(Application.persistentDataPath);
        }
        [MenuItem("Tools/打开常用文件夹/打开打包的AssetBundle目录")]
        public static void OpenBundleDataPath()
        {
            Application.OpenURL(Application.dataPath+"/../BuildBundles");
        }

       public static void CopyToStreamingAssets()
        {
           
            AssetDatabase.Refresh();
        }

**Comment by mister91jiao** [comment]
已加
