### ISSUE TITLE
热更路径

### ISSUE THREAD

**Issue by clksaaa** [mister91jiao/BundleMaster_IntegrateETTask#7]
今天测试在window打包运行的时候下面这个没改回去  资源被更新到了执行文件的目录层级
 如果在tools的配置面板加一个进入沙盘目录的按钮 就不用手动更改热更路径了
在android环境的时候也不会忘了改回去而出错  是不是更方便一些
//重新配置热更路径
        AssetComponentConfig.HotfixPath = Application.dataPath + "/../HotfixBundles/";

**Comment by mister91jiao** [comment]
你可以可以自己加个宏来判断这里
